(setq create-lockfiles nil)
(delete-selection-mode t)
(spacemacs/toggle-camel-case-motion-globally-on)

(defun mshogin-split-and-helm-mini ()
  (interactive)
  (spacemacs/split-window-horizontally-and-switch)
  (helm-mini)
  )
(defun mshogin-split-h-and-helm-mini ()
  (interactive)
  (spacemacs/split-window-vertically-and-switch)
  (helm-mini)
  )
(global-set-key (kbd "M-m w /") 'mshogin-split-and-helm-mini)
(global-set-key (kbd "M-m w -") 'mshogin-split-h-and-helm-mini)

(setq eshell-prompt-function
      (lambda ()
        (concat (format-time-string "%Y-%m-%d %H:%M" (current-time))
                (if (= (user-uid) 0) " # " " $ "))))
